version: "3.3"

services:

  mongo:
    image: mongo
    restart: always
    ports:
    - 27018:27017

  redis:
    image: redis
    restart: always
    ports:
    - 6378:6379

  mongoexpress:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
    - 8081:8081    

  scraper:
    image: tripmadam/dba-scraper-stef
    ports: 
    - 5000:5000