version: "3.3"

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
    - 27018:27017

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
    - 6378:6379